### ISSUE TITLE
Feature request: obey target column position in jump

### ISSUE THREAD

**Issue by andymass** [weilbith/nvim-lsp-smag#1]
Currently, if you have "set nosol" the column which is jumped to on `c-]` is unpredictable, and not the location of the target symbol.

There are two ways to achieve this;  one is to use a simple line/column pattern like `\%23l\%20c`.  The other is to use a command like `call cursor(3, 4)|;"` (including the weird trailing pipe semicolon quote).

**Comment by andymass** [comment]
I am not very familiar with lua or neovim's lsp implementation. but I gave it a go.

```diff
diff --git a/lua/lsp_smag/tags/formatting.lua b/lua/lsp_smag/tags/formatting.lua
index 1e1ee66..26d854e 100644
--- a/lua/lsp_smag/tags/formatting.lua
+++ b/lua/lsp_smag/tags/formatting.lua
@@ -1,4 +1,5 @@
 local vim = vim
+local lsp = vim.lsp
 local api = vim.api

 local M = {}
@@ -21,10 +22,11 @@ function M.lsp_location_to_tag(name, kind, lsp_location)
     local uri = lsp_location.uri or lsp_location.targetUri
     local range = lsp_location.range or lsp_location.targetRange
     local line = range.start.line + 1
+    local col = lsp.util._get_line_byte_from_position(0, range.start)

     return {
         name = name,
-        cmd = tostring(line),
+        cmd = '/\\%' .. tostring(line) .. 'l\\%' .. tostring(col+1) .. 'c/',
         kind = kind .. " ", -- add a gap to the tag name
         filename = get_path(uri),
         user_data = read_line(uri, line)
```

**Comment by weilbith** [comment]
Hey, thanks for the issue. You really have an eye for details!
Would you mind to open a PR? Than I can put my nitpicks as review and also test it myself easily. Thanks! :pray:
