### ISSUE TITLE
Hangs forever on latest neovim

### ISSUE THREAD

**Issue by vilari-mickopf** [weilbith/nvim-lsp-smag#6]
I am using nightly version, but the same thing happens with the release version (0.6.0)

```nvim --version```
```
NVIM v0.7.0-dev+660-gd3585e0ec
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM
-DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-103

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

or 

```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by vilari-mickopf** [comment]
It seems that [neovim 0.6](https://github.com/neovim/neovim/releases/tag/v0.6.0) has the feature of this plugin integrated in lsp. It can be enabled with:
```vim
set tagfunc=v:lua.vim.lsp.tagfunc
```

**Comment by weilbith** [comment]
> It seems that [neovim 0.6](https://github.com/neovim/neovim/releases/tag/v0.6.0) has the feature of this plugin integrated in lsp. It can be enabled with:
> 
> ```viml
> set tagfunc=v:lua.vim.lsp.tagfunc
> ```

I've seen it. But that is only partially true. Though I agree that many people might wanna skip this plugin in advantage of the in-built function. The remaining "advantage" here is that you also can get the declaration, implementation and type definition as well. This might not be helpful for too many programming languages. But because of that, this repository is not yet archived.
After all I appreciate that these features are native now. Having no need for this plugin is great. I always like to depracture my plugins for this reason.

**Comment by weilbith** [comment]
To the original issue: do you have any ideas/hints or so why this happens? To my knowledge `0.6` should not affect this plugin. 🤔

**Comment by weilbith** [comment]
So I just installed the latest nightly build. It just works for me. Could you provide me with an example?

**Comment by weilbith** [comment]
Though it seems to have become more slow.... 🤔

**Comment by vilari-mickopf** [comment]
You are right, I went through my configuration, disabling plugins one by one and it seems that [psliwka/vim-smoothie](https://github.com/psliwka/vim-smoothie) plugin is causing the problem. Looks like a recursive map or smth, but it's weird because I've disabled all default mappings from smoothie. Anyway, integrated lsp.tagfunc fully suits my needs for now, since it will also jump between function declaration and definition in my c/c++ files and that's all I need. However, lots of thanks for this awesome plugin, I couldn't live without it for the last few months:)

**Comment by weilbith** [comment]
Back from vacation:
Glad to hear your setup works again (does it?). And thanks for the nice words. I kinda hope to archive this plugin soon. ✌🏾

**Comment by vilari-mickopf** [comment]
It works^^

**Comment by weilbith** [comment]
Okay. 😅
